name: Deploy FastAPI to Server

on:
  push:
    branches:
      - main  # main 브랜치로 푸시되면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USER }}/your-fastapi-app  # FastAPI 프로젝트 경로
            
            # 최신 코드 가져오기
            git pull origin main
            
            # 가상 환경 활성화 및 패키지 설치
            source venv/bin/activate
            pip install -r requirements.txt

            # FastAPI 서버 재시작
            pkill -f "uvicorn" || true  # 기존 FastAPI 서버 종료
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > fastapi.log 2>&1 &
          EOF
